version: '3'
services:
  backend:
    image: anshtshipppen/avvship:backend
    container_name: foneaceb
    working_dir: /dock
    command: yarn dev
    ports:
      - "3000:3000"

  frontend:
    image: anshtshipppen/avvship:frontend
    container_name: foneacef
    ports:
      - "5173:5173"
    depends_on:
      - backend

